theme: jekyll-theme-minimal
remote_theme: pmarsceill/just-the-docs
Markdown: kramdown
plugins:
  - jekyll-avatar
  - jekyll-time-to-read

footer_content: "Copyright &copy; 2020 Crisis @ Christmas. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true 
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/rw-martin/infographic"
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately