theme: jekyll-theme-minimal
remote_theme: pmarsceill/just-the-docs
Markdown: kramdown
plugins:
  - jekyll-avatar
  - jekyll-time-to-read

footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true 
last_edit_time_format: "%b %e %Y at %I:%M %p"
